[package]
name = "side"
version = "0.1.0"
authors = ["FelixMo42 <felix@tacocat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
